def print_menu():
    print("╔═══════════════════════════════════════════════════════╗")
    print("║         📊 CHƯƠNG TRÌNH XỬ LÝ FILE CSV                ║")
    print("╠═══════════════════════════════════════════════════════╣")
    print("║ 1.  Xóa chuỗi theo cột hoặc toàn bộ                   ║")
    print("║ 2.  Thống kê giá trị duy nhất trong 1 cột             ║")
    print("║ 3.  Tìm và thay thế trong cột hoặc toàn bộ            ║")
    print("║ 4.  Chuyển hoa/thường dữ liệu trong cột               ║")
    print("║ 5.  Xóa dòng rỗng hoặc chứa chuỗi                     ║")
    print("║ 6.  Gộp hoặc tách cột                                 ║")
    print("║ 7.  Lọc dữ liệu theo điều kiện                        ║")
    print("║ 8.  Thống kê (tổng, trung bình...) theo cột           ║")
    print("║ 9.  Sắp xếp theo cột                                  ║")
    print("║ 10. Xử lý dữ liệu thời gian                           ║")
    print("║ 11. Xuất ra định dạng khác (JSON, TXT...)             ║")
    print("║ 12. Kiểm tra dữ liệu lỗi, thiếu                       ║")
    print("║ 13. Xem nhanh (Preview 5 dòng đầu/cuối)               ║")
    print("║ 14. Đổi đường dẫn file CSV                            ║")
    print("║ 15. Vẽ biểu đồ (line/bar/pie) từ cột dữ liệu          ║")
    print("║ 16. Tìm và xóa dòng trùng lặp (toàn bộ hoặc theo cột) ║")
    print("║ 17. Gộp nhiều file CSV thành 1 file                   ║")
    print("║ 18. Tách file CSV thành nhiều phần nhỏ                ║")
    print("║ 19. Tạo báo cáo phân tích tự động từ dữ liệu          ║")
    print("║ 20. Tạo cột mới theo công thức từ các cột hiện có     ║")
    print("║ 21. Chuẩn hóa dữ liệu trong cột                       ║")
    print("║ 22. Phát hiện loại dữ liệu trong từng cột             ║")
    print("║ 23. Từ Excel/PDF sang CSV                             ║")
    print("║ 24. Tìm kiếm nâng cao theo nhiều điều kiện            ║")
    print("║ 0.  Thoát chương trình                                ║")
    print("╚═══════════════════════════════════════════════════════╝")
